### ISSUE TITLE
wait ur code~~thx~

### ISSUE THREAD

**Issue by Ricelll** [liyunsheng13/dcd#1]
Hi, Please as soon as possible release the code~~

**Comment by liyunsheng13** [comment]
I'm cleaning the code and will release everything next week.

**Comment by Ricelll** [comment]
Thx!!!!!

**Comment by liyunsheng13** [comment]
The code has been release. Let me know if there is any bugs.

**Comment by nanmehta** [comment]
sir, can u please let me know , wherein the code, svd decomposition is done.

**Comment by liyunsheng13** [comment]
The matrix decomposition is not clearly done with SVD. Instead, we use three matrics P \Phi Q that contain weight parameters to implement DCD.

**Comment by nanmehta** [comment]
okay sir, I m not able to relate the code from  the proposed paper, can you please help me out.
![doubt_dc](https://user-images.githubusercontent.com/67276550/116688261-137c3480-a9d4-11eb-990f-199bcb484c3e.PNG)
   


I could not understand, where in the code that addition operation between the static and dynamic kernels is being performed.

**Comment by liyunsheng13** [comment]
In the code, I do not synthesize kernel. Instead, I use \lambda W0 and P\PhiQ to extract features separately and then add the feature.

**Comment by nanmehta** [comment]
thanks for your prompt reply, sir.
Actually, sir, I have a lot of queries and I hope they might help the others viewing this code.
1. Sir, you have not mentioned anywhere in the code about the hsigmoid layer, used in the code.
2. what is the variable name used to denote lamda and W0.
3. Since, in the code so many classes have been defined, which exactly corresponds to the DYNAMIC CONVOLUTION DECOMPOSITION.
4. According, to my understanding the class conv.dy is being used for DCD but, sir my query in that is a)   as u above said that you have defined separately all the features (\lambda W0 and P\PhiQ) and then added, I could not get where all the features are being added.

please , help me.

**Comment by liyunsheng13** [comment]
Everything you asked is defined in the class DYModule.

**Comment by nanmehta** [comment]
thanks a lot sir!
