### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by HzZHoO** [liyunsheng13/dcd#4]
Thanks for your great work~
I have a question about the code
`out = self.bn2(torch.matmul(phi, out)) + out`
I can't understand the residual part of the code above, is this means **phi * Q * x + Q * x** ? Is this residual part necessary?
Looking forward to your reply

**Comment by liyunsheng13** [comment]
The expression should be y=p(\Phi+I)Qx, where 'I' is an identity matrix. It makes the training process more stable. If you drop 'I' or even drop all the BN layers, the DCD still works but you might get different accuracy if you train the model multiple times.   Since all the operations are linear, keeping 'I' does not influence the analyse on the matrix decomposition. I suggest to keep it.

**Comment by HzZHoO** [comment]
Very thanks for your detailed explanation, it is very helpful to me!
